# Generated by Django 6.0.2 on 2026-03-17 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id_cuestionario', models.AutoField(db_column='ID_cuestionario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateField()),
                ('activo_estatus', models.BooleanField()),
            ],
            options={
                'db_table': 'cuestionario',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(db_column='ID_pregunta', primary_key=True, serialize=False)),
                ('enunciado', models.TextField()),
                ('figura_correcta_canva', models.CharField(blank=True, max_length=50, null=True)),
                ('plantilla_url', models.TextField(blank=True, null=True)),
                ('retro_trazado', models.TextField(blank=True, null=True)),
                ('retro_opciones', models.TextField(blank=True, null=True)),
                ('nivel', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'pregunta',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='ID_usuario', primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('apellido_usuario', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('id_intento', models.AutoField(db_column='ID_intento', primary_key=True, serialize=False)),
                ('fecha_intento', models.DateField()),
                ('calificacion_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cuestionario', models.ForeignKey(db_column='ID_cuestionario', on_delete=django.db.models.deletion.PROTECT, related_name='intentos', to='api.cuestionario')),
                ('estudiante', models.ForeignKey(db_column='ID_estudiante', on_delete=django.db.models.deletion.PROTECT, related_name='intentos', to='api.usuario')),
            ],
            options={
                'db_table': 'intento',
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id_opcion', models.AutoField(db_column='ID_opcion', primary_key=True, serialize=False)),
                ('texto_opcion', models.CharField(max_length=255)),
                ('es_correcta', models.BooleanField()),
                ('pregunta', models.ForeignKey(db_column='ID_pregunta', on_delete=django.db.models.deletion.PROTECT, related_name='opciones', to='api.pregunta')),
            ],
            options={
                'db_table': 'opcion',
            },
        ),
        migrations.CreateModel(
            name='CuestionarioPregunta',
            fields=[
                ('pk', models.CompositePrimaryKey('cuestionario', 'pregunta', blank=True, editable=False, primary_key=True, serialize=False)),
                ('cuestionario', models.ForeignKey(db_column='ID_cuestionario', on_delete=django.db.models.deletion.PROTECT, to='api.cuestionario')),
                ('pregunta', models.ForeignKey(db_column='ID_pregunta', on_delete=django.db.models.deletion.PROTECT, to='api.pregunta')),
            ],
            options={
                'db_table': 'cuestionario_preguntas',
            },
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='preguntas',
            field=models.ManyToManyField(related_name='cuestionarios', through='api.CuestionarioPregunta', to='api.pregunta'),
        ),
        migrations.CreateModel(
            name='RespuestaEstudiante',
            fields=[
                ('pk', models.CompositePrimaryKey('intento', 'pregunta', blank=True, editable=False, primary_key=True, serialize=False)),
                ('datos_trazado', models.TextField(blank=True, null=True)),
                ('prediccion_ia', models.CharField(blank=True, max_length=50, null=True)),
                ('calificacion_pregunta', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('retro_individual', models.TextField(blank=True, null=True)),
                ('intento', models.ForeignKey(db_column='ID_intento', on_delete=django.db.models.deletion.PROTECT, to='api.intento')),
                ('opc_select', models.ForeignKey(blank=True, db_column='ID_opc_select', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.opcion')),
                ('pregunta', models.ForeignKey(db_column='ID_pregunta', on_delete=django.db.models.deletion.PROTECT, to='api.pregunta')),
            ],
            options={
                'db_table': 'respuesta_estudiante',
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='usuario_creador',
            field=models.ForeignKey(blank=True, db_column='ID_usuario_creador', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preguntas_creadas', to='api.usuario'),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='profesor',
            field=models.ForeignKey(db_column='ID_profesor', on_delete=django.db.models.deletion.PROTECT, related_name='cuestionarios_creados', to='api.usuario'),
        ),
    ]
