# Generated by Django 6.0.2 on 2026-04-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuestionariopregunta",
            name="cuestionario",
            field=models.ForeignKey(
                db_column="ID_cuestionario",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.cuestionario",
            ),
        ),
        migrations.AlterField(
            model_name="intento",
            name="cuestionario",
            field=models.ForeignKey(
                db_column="ID_cuestionario",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intentos",
                to="api.cuestionario",
            ),
        ),
        migrations.AlterField(
            model_name="respuestaestudiante",
            name="intento",
            field=models.ForeignKey(
                db_column="ID_intento",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.intento",
            ),
        ),
    ]
