# Generated by Django 6.0.2 on 2026-04-10 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cascade_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshTokenSession',
            fields=[
                ('id_refresh_token', models.AutoField(db_column='ID_refresh_token', primary_key=True, serialize=False)),
                ('jti', models.CharField(max_length=36, unique=True)),
                ('token_hash', models.CharField(max_length=64)),
                ('expira_en', models.DateTimeField()),
                ('revocado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='ID_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='api.usuario')),
            ],
            options={
                'db_table': 'refresh_token_session',
            },
        ),
    ]
