# Generated by Django 6.0.2 on 2026-04-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_refreshtokensession'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaestudiante',
            name='precision_ia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
